spring.application.name=backend

spring.datasource.url=jdbc:sqlite:bd_hackathon.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=mySecretKey1234567890123456789012345678901234567890