spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@financeai_high?TNS_ADMIN=/app/wallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ADMIN}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}
datascience.api.base-url=${DATASCIENCE_API_BASE_URL:http://python-ia:8000}